# Generated by Django 3.1.3 on 2021-08-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderer',
            name='count',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderer',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
