# Generated by Django 3.1.3 on 2021-08-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210803_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderer',
            name='address',
        ),
        migrations.AddField(
            model_name='orderer',
            name='address1',
            field=models.CharField(default='addressl line 1', max_length=200),
        ),
        migrations.AddField(
            model_name='orderer',
            name='address2',
            field=models.CharField(default='addressl line 2', max_length=200),
        ),
        migrations.AddField(
            model_name='orderer',
            name='address3',
            field=models.CharField(default='addressl line 3', max_length=200),
        ),
        migrations.AddField(
            model_name='orderer',
            name='address4',
            field=models.CharField(default='addressl line 4', max_length=200),
        ),
    ]
