# Generated by Django 3.1.3 on 2021-08-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210803_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderer',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='orderer',
            name='address4',
        ),
    ]
