# Generated by Django 3.1.3 on 2021-08-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
